// app/lib/callAnalysisFieldMap.ts

export const CALL_ANALYSIS_FIELD_LABELS: Record<string, string> = {
    started_at: "Start Time and Date",
    status: "Call Status",
    call_type: "Call Type",
    llm: "LLM",
    stt: "STT",
    tts: "TTS",
    llm_cost: "LLM Cost",
    stt_cost: "STT Cost",
    tts_cost: "TTS Cost",
    cost: "Pipeline Cost",
    language: "Language",
    call_quality_score: "Call Quality Score",
    sentiment: "Sentiment",
    script_adherence_score: "Script Adherence",
    violations: "Violations",
    call_disposition: "Disposition",
    call_transfer: "Transferred",
    escalation_flag: "Escalated",
    ai_confidence_score: "AI Confidence",
    nlp_error_rate: "NLP Error Rate",
    intent_detected: "Intent Detected",
    intent_success_rate: "Intent Success Rate",
    average_intent_turn: "Avg Intent Turn",
    lead_score: "Lead Score",
    conversion_flag: "Converted",
    upsell_flag: "Upsold",
    cross_sell_flag: "Cross-sold",
    survey_score: "Survey Score",
    compliance_risk_score: "Compliance Risk",
    keyword_alert_count: "Keyword Alerts",
    pci_dss_sensitive_data_detected: "PCI DSS Sensitive Data",
    gdpr_data_request: "GDPR Data Request",
    customer_engagement_score: "Engagement Score",
    interruption_count: "Interruptions",
    reviewer_comments: "Reviewer Comments",
    follow_up_date_time: "Follow-up Time",
    call_direction: "Call Direction",
    call_duration: "Call Duration(sec)",
    average_latency: "Avg. Latency(sec)",
  };
  